config/routes.rb
Rails.application.routes.draw do
  root 'visualizations#welcome'

  #json requests
  get 'surnames/histogram' => "surnames#histogram", :as => "surnames_histogram"
  get 'surnames/directed_graph_small' => "surnames#directed_graph_small", 
    :as => "surnames_directed_graph"
  get 'surnames/directed_graph_large' => "surnames#directed_graph_large", 
    :as => "surnames_directed_graph_large"

  #chart pages
  get 'histogram' => 'visualizations#histogram', :as => "histogram"
  get 'directed_graph_small' => 'visualizations#directed_graph_small', 
    :as => "directed_graph_small"
  get 'directed_graph_large' => 'visualizations#directed_graph_large', 
    :as => "directed_graph_large"
  get 'add_and_remove' => 'visualizations#add_and_remove', 
    :as => "add_and_remove"
  get 'add_and_remove_small' => 'visualizations#add_and_remove_small', 
    :as => "add_and_remove_small"
  get 'add_and_remove_large' => 'visualizations#add_and_remove_large', 
    :as => "add_and_remove_large"
  get 'about' => 'visualizations#about', :as => "about"
  get 'welcome' => 'visualizations#welcome', :as => "welcome"

  resources :surnames

end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController
  def histogram 
  end

  def add_and_remove
  end

  def about
  end

  def welcome
  end

  def add_and_remove_small
    @surnames = Surname.all.limit(10)
    @nodes = Surname.small_graph_nodes
    @edges = Surname.small_graph_links
    @components = Surname.small_graph_components.count
  end

  def add_and_remove_large
    @surnames = Surname.all
    @nodes = Surname.large_graph_nodes
    @edges = Surname.large_graph_links
    @components = Surname.large_graph_components.count
  end

  def directed_graph_small
    @nodes = Surname.small_graph_nodes.count
    @edges = Surname.small_graph_links.count
    @components = Surname.small_graph_components.count
    @surname = Surname.new
    @surnames = Surname.all
  end

  def directed_graph_large
    @nodes = Surname.nodes.count
    @edges = Surname.all.count
    @components = Surname.components.count
    @surname = Surname.new
    @surnames = Surname.all
  end


  def miserables
    @@data = File.read("db/miserables.json")
    render :json => @@data
  end
end

app/helpers/visualizations_helper.rb
module VisualizationsHelper
end

app/views/visualizations/about.html.erb
<h1> ついて ・ About </h1>
<div class="about">
  <section>
  <h1 style="padding-left:10px">Concepts From Graph Theory</h1>
  <div class="row">
    <div class="col-md-4" id="graph-theory">
      <%= image_tag "/images/breadth_first_search.gif" %>
      <%= image_tag "/images/node.png", :id => "node" %>
    </div>
    <div class="col-md-8">
      <br>
      <br>
      <h4><b>Components</b> are groups of connected nodes in a graph. Think of them as islands of interconnected data.</h4>
      <br>
      <h4>In order to calculate the number of components in a given graph, we implemented the <b>breadth-first search</b> algorithm.</h4>
      <br>
      <br>
      <h4>In our large graph, there are <b>80 characters</b> yet only <b>7 components</b>.  Most of the nodes are linked to one large central component.  This conveys that most common japanese names are related combinations of the same small set of kanji.</h4>
      <br>
      <h4>We noticed that <b>田</b> (pronounced "ta", meaning "rice field") was by far the most connected datum in the large graph, occuring in 25 names -- a quarter of our sample. This perhaps speaks to Japan's heritage as an agrarian society.</h4>   
    </div>
  </div>
</section>
<section class="gray">
  <h1 style="text-align:right;padding-right:10px">Technologies Used</h1>
  <div class="col-md-8">
    <br>
    <h4>We used <b>AJAX</b> to access information from the database in our Javascript layer. <b>D3.js</b> provides a built-in .json() function, which we used to access our own json endpoints.</h4>
    <br>
    <h4>Kanji definitions were dynamically scraped and seeded using <b>Nokogiri</b> and a custom <b>rake</b> task.</h4>
    <br>
    <h4>Our <b>javascript</b> is mostly procedural.  However, in order to implement the dynamic graph, we explored <b>object-oriented javascript</b>.  Each page load instantiates a Graph object, which maintains the state of the graph as nodes are added and removed.</h4>
    </br>
    <h4>We used <b>jQuery</b> to bind highlight and tooltip effects to each node's hover event.</h4>
    <br>
    <h4>The trusty <b>Rails stack</b> holds it all together.</h4>
  </div>
  <div class="col-md-4 logos">
    <div class="center">
      <%= image_tag "/images/ruby.svg", :id => "ruby" %>
      <div id="nokogiri">鋸<p>Nokogiri</p></div>
      <%= image_tag "/images/javascript.svg", :id => "javascript" %>
      <%= image_tag "/images/jquery.svg", :id => "jquery" %>
      <%= image_tag "/images/rails.png" %>
    </div>
  </div>
</section>
<section>
  <h1 style="padding-left:10px;padding-top:10px">Creators</h1>
  <div class="col-md-6 bio">
    <%= image_tag "/images/lauraconwill.jpg", class:"biopic"%>
    <h2>Laura Conwill</h2>
    <h4>ローラ・コンウィル</h4>
    <div class="social">
      <a href="http://www.linkedin.com/pub/laura-conwill/87/286/9b"><%= fa_icon("linkedin 2x")%></a>
      <span></span>
      <a href="https://twitter.com/eleichsea"><%= fa_icon("twitter 2x")%></a>
      <span></span>
      <a href="https://github.com/lauraconwill"><%= fa_icon("github 2x")%></a>
    </div>
    <br>
    <h4>Laura learned Japanese growing up in Tokyo.  She graudated from Caltech in 2012 and attended the Flatiron School in 2014.  Her interests include photography, hacking and browsing the collection at the Met.
  </div>
  <div class="col-md-6 bio">
    <%= image_tag "/images/michaelprouty.png", class:"biopic" %>
    <h2>Michael Prouty</h2>
    <h4>マイケル・プラウティ</h4>
    <div class="social">
      <a href="https://linkedin.com/in/mprouts"><%= fa_icon("linkedin 2x")%></a>
      <span></span>
      <a href="https://twitter.com/MProuts"><%= fa_icon("twitter 2x")%></a>
      <span></span>
      <a href="https://github.com/MProuts"><%= fa_icon("github 2x")%></a>
    </div>
    <br>
    <h4>Michael is a musician, language learner, and hacker.  He graduated from Pomona College in 2011 and attended the Flatiron School in 2014.  His interests include modernist literature, Mahler, and long walks in the park.</h4>
  </div>
</section>
<%= link_to "<", add_and_remove_large_path, :class => "navigation-left", :id => "about" %>
</div>

app/views/visualizations/add_and_remove_large.html.erb
<h1>五　Iteration 5</h1>
<div class="row">
  <div class="col-md-8" id="directed_graph_dynamic_large">
  </div>
  <div class="col-md-4 well stats" id="statistics">
    <h2>Large Dynamic Graph</h2>
    <p>(click below)</p>
    <br>
    <div>
    <table class="table">
      <tr>
        <th>Nodes</th>
        <th>Edges</th>
        <th>Components</th>
      </tr>
      <tr>
        <td><%= @nodes.count %></td>
        <td><%= @edges.count %></td>
        <td><%= @components %></td>
      </tr>
    </table>
    </div>
    <p class="button-group-label">Characters:</p>
    <div id='kanjis'>
      <% @nodes.each do |node| %>
        <div class='ck-button'>
          <label class='ck-button'><input type="checkbox" name="name" class="kanji_checkbox2" value="<%= node[:name] %>" checked><span><%= node[:name] %></span></label>
        </div>
      <% end %>
    </div>
    <%= link_to ">", about_path, :class => "navigation-right" %>
    <%= link_to "<", directed_graph_large_path, :class => "navigation-left" %>
    <p class="footnote">*dataset: 96 common Japanese surnames</p>
  </div>
</div>

app/views/visualizations/add_and_remove_small.html.erb
<h1>三　Iteration 3</h1>
<div class="row">
  <div class="col-md-8" id="directed_graph_dynamic">
  </div>
  <div class="col-md-4 well stats" id="statistics">
    <h2>Dynamic Graph</h2>
    <p>(click below)</p>
    <br>
    <div>
    <table class="table">
      <tr>
        <th>Nodes</th>
        <th>Edges</th>
        <th>Components</th>
      </tr>
      <tr>
        <td><%= @nodes.count %></td>
        <td><%= @edges.count %></td>
        <td><%= @components %></td>
      </tr>
    </table>
    </div>
    <p class="button-group-label">Names:</p>
    <div id='surnames'>
      <% @surnames.each do |surname| %>
        <div class='ck-button'>
          <label class='ck-button'><input type="checkbox" name="name" class="name_checkbox" value="<%= surname.name %>" checked><span><%= surname.name %></span></label>
        </div>
      <% end %>
    </div>
    <br>
    <p class="button-group-label">Characters:</p>
    <div id='kanjis'>
      <% @nodes.each do |node| %>
        <div class='ck-button'>
          <label class='ck-button'><input type="checkbox" name="name" class="kanji_checkbox" value="<%= node[:name] %>" checked><span><%= node[:name] %></span></label>
        </div>
      <% end %>
    </div>
    <%= link_to ">", directed_graph_large_path, :class => "navigation-right" %>
    <%= link_to "<", directed_graph_small_path, :class => "navigation-left" %>
    <p class="footnote">*dataset: 10 common Japanese surnames</p>
  </div>
</div>

app/views/visualizations/directed_graph.html.erb
<div class="row">
  <div class="col-md-8" id="diagram">
  </div>
  <div class="col-md-4 well" id="statistics">
    <h2>Statistics</h2>
    <ul class="list-unstyled">
      <li><h4>Nodes: <%= @nodes %></h4></li>
      <li><h4>Edges: <%= @edges %></h4></li>
      <li><h4>Components: <%= @components %></h4></li>
    </ul>
    <br>
    <br>
    <%= render :partial => 'surnames/remote_form' %>
  </div>
</div>
<div class="row">
</div>

app/views/visualizations/directed_graph_large.html.erb
<h1>四　Iteration 4</h1>
<div class="row">
  <div class="col-md-8" id="directed_graph_large">
  </div>
  <div class="col-md-4 well stats" id="statistics">
    <h2><span style="white-space:nowrap">Co-occurrence</span> With Translations</h2>
    <ul class="list-unstyled">
      <li><h4></h4></li>
    </ul>
    <p>(scroll)</p>
    <p>(hover over nodes)</p>
    <br>
    <table class="table">
      <tr>
        <th>Nodes</th>
        <th>Edges</th>
        <th>Components</th>
      </tr>
      <tr>
        <td><%= @nodes %></td>
        <td><%= @edges %></td>
        <td><%= @components %></td>
      </tr>
    </table>
    <br>
    <br>
    <%= link_to ">", add_and_remove_large_path, :class => "navigation-right" %>
    <%= link_to "<", add_and_remove_small_path, :class => "navigation-left" %>
    <p class="footnote">*dataset: 100 common Japanese surnames</p>
  </div>
</div>
<div class="row">
</div>

app/views/visualizations/directed_graph_small.html.erb
<h1>二　Iteration 2</h1>
<div class="row">
  <div class="col-md-8" id="directed_graph_small">
  </div>
  <div class="col-md-4 well stats" id="statistics">
    <h2>Character <span style="white-space: nowrap">Co-occurrence</span></h2>
    <p>(drag nodes)</p>
    <%= link_to ">", add_and_remove_small_path, :class => "navigation-right" %>
    <%= link_to "<", histogram_path, :class => "navigation-left" %>
    <p class="footnote">*dataset: 10 common Japanese surnames</p>
  </div>
</div>

app/views/visualizations/histogram.html.erb
<h1>一　Iteration 1</h1>
<div class="row">
  <div class="col-md-8" id="histogram">
    <div class="chart"></div>
  </div>
  <div class="col-md-4 well stats" id="statistics">
    <h2>Character Frequency</h2>
    <p>(scroll)</p>
    <br>
    <br>
    <%= link_to ">", directed_graph_small_path, :class => "navigation-right" %>
    <%= link_to "<", root_path, :class => "navigation-left" %>
    <p class="footnote">*dataset: 100 common Japanese surnames</p>
  </div>
</div>

app/views/visualizations/welcome.html.erb
<h1>歓迎 Welcome</h1>
<div class="row">
  <div class="col-md-4 welcome">
    <p class="big-characters">漢字</p>
    <div class="caption">
    <fieldset>
      <legend>Background</legend>
      <p>This project visualizes relationships between kanji.</p>
      <p><em>Kanji</em> are a subset of pictorgraphic Chinese characters that are used in the modern Japanese writing system. Each kanji represents a concept, verb or noun.</p>
    </div>
  </div>
  <div class="col-md-4 welcome" id="welcome">
    <div id="objectives"></div>
    <div class="caption">
      <legend>Objectives</legend>
      <ul>
        <li>Experiment with D3.js</li>
        <li>Integrate Object-Oriented Javascript into the Rails stack</li> 
      </ul>
    </div>
  </div>
  <div class="col-md-4 stats welcome" id="statistics">
    <p id="infinity">∞</p>
    <p id="arrow">↓</p>
    <p id="small-characters">田山中村川口</p>
    <div class="caption">
      <legend>Dataset</legend>
      <p>There are over 50,000 characters in the Japanese language. We limited our exploration to characters that make up the 100 most common Japanese names.</p>
    </fieldset>
    </div>
    <%= link_to ">", histogram_path, :class => "navigation-right" %>
  </div>
</div>