config/routes.rb
Rails.application.routes.draw do
  root 'visualizations#welcome'

  #json requests
  get 'surnames/histogram' => "surnames#histogram", :as => "surnames_histogram"
  get 'surnames/directed_graph_small' => "surnames#directed_graph_small", 
    :as => "surnames_directed_graph"
  get 'surnames/directed_graph_large' => "surnames#directed_graph_large", 
    :as => "surnames_directed_graph_large"

  #chart pages
  get 'histogram' => 'visualizations#histogram', :as => "histogram"
  get 'directed_graph_small' => 'visualizations#directed_graph_small', 
    :as => "directed_graph_small"
  get 'directed_graph_large' => 'visualizations#directed_graph_large', 
    :as => "directed_graph_large"
  get 'add_and_remove' => 'visualizations#add_and_remove', 
    :as => "add_and_remove"
  get 'add_and_remove_small' => 'visualizations#add_and_remove_small', 
    :as => "add_and_remove_small"
  get 'add_and_remove_large' => 'visualizations#add_and_remove_large', 
    :as => "add_and_remove_large"
  get 'about' => 'visualizations#about', :as => "about"
  get 'welcome' => 'visualizations#welcome', :as => "welcome"

  resources :surnames

end

app/models/surname.rb
class Surname < ActiveRecord::Base
  validates :name, :presence => true
  validate :ensure_name_is_kanji_only
  attr_accessor :large_graph_char_data, :large_graph_nodes, :large_graph_names, :small_graph_names

  def self.histogram_data
    names = self.pluck(:name)
    kanji = names.join("").split("")
    hash = kanji.group_by { |v| v }
    result = hash.map{|key, value| {:kanji => key, :value => value.count}}.sort_by { |hsh| hsh[:value] }.reverse
  end

  def self.large_graph_data
    { nodes: self.large_graph_nodes, 
      links: self.large_graph_links }
  end

  def self.small_graph_data
    { nodes: self.small_graph_nodes, 
      links: self.small_graph_links }
  end

  def self.nodes
    kanji_array = self.pluck(:name).join("").split("").uniq
    kanji_array.each_with_index.map do |name, index| 
      { name: name, 
        id: index, 
        meaning: Character.find_by(:name => name).meaning }
    end
  end

  def self.links
    nodes = self.nodes.map {|hsh| hsh[:name] }
    self.pluck(:name).map { |name| { source: nodes.index(name[0]),
                                     target: nodes.index(name[1]) } }
  end

  def self.small_graph_names
    @small_graph_names ||= self.limit(10).pluck(:name)
  end

  def self.large_graph_names
    @large_graph_names ||= self.all.pluck(:name)
  end

  def self.small_graph_nodes
    kanji_array = self.small_graph_names.join("").split("").uniq
    kanji_array.each_with_index.map do |name, index| 
      { name: name,
        id: index,
        meaning: Character.find_by(:name => name).meaning }
    end
  end

  # previous version
  def self.busted_large_graph_nodes
    kanji_array = self.large_graph_names.join("").split("").uniq
    kanji_array.each_with_index.map do |name, index| 
      { name: name,
        id: index,
        meaning: Character.find_by(:name => name).meaning }
    end
  end

  def self.get_large_graph_chars(kanji_array)
    @large_graph_char_data ||= Character.where(:name => kanji_array)
  end


  def self.large_graph_nodes
    kanji_array = self.large_graph_names.join("").split("").uniq
    all_characters = get_large_graph_chars(kanji_array)
    all_characters.each_with_index.map do |char_data, index|
      {name: char_data.name,
       id: index,
       meaning: char_data.meaning
      }
    end
  end

  def self.small_graph_links
    # nodes = self.small_graph_nodes.map {|hsh| hsh[:name] }
    # self.limit(10).pluck(:name).map { |name| { source: nodes.index(name[0]),
    #                                 target: nodes.index(name[1]) } }
    nodes_with_ids = self.small_graph_names.map{ |name| {source: self.small_graph_nodes.select{|hsh| hsh[:name] == name[0]}[0][:id],
                                                         target: self.small_graph_nodes.select{|hsh| hsh[:name] == name[1]}[0][:id]}}
  end

  def self.large_graph_links
    nodes_with_ids = self.large_graph_names.map{ |name| {source: self.large_graph_nodes.select{|hsh| hsh[:name] == name[0]}[0][:id],
                                                         target: self.large_graph_nodes.select{|hsh| hsh[:name] == name[1]}[0][:id]}}
  end


  def self.edges
    self.links.collect{|hsh| [hsh[:source], hsh[:target]].sort}
  end

  def self.small_graph_edges
    self.small_graph_links.collect{|hsh| [hsh[:source], hsh[:target]].sort}
  end

  def self.large_graph_edges
    self.large_graph_links.collect{|hsh| [hsh[:source], hsh[:target]].sort}
  end

  def self.components
    edges = self.edges
    components = []
    while edges.any? 
      component = edges.shift
      while edges.select { |edge| !(edge & component).empty? }.any?

        component << edges.select { |edge| !(edge & component).empty? }
        edges.delete_if { |edge| !(edge & component).empty? }
        component = component.flatten.uniq
      end
      components << component
    end
    components
  end

  def self.small_graph_components
    edges = self.small_graph_edges
    components = []
    while edges.any? 
      component = edges.shift
      while edges.select { |edge| !(edge & component).empty? }.any?
        component << edges.select { |edge| !(edge & component).empty? }
        edges.delete_if { |edge| !(edge & component).empty? }
        component = component.flatten.uniq
      end
      components << component
    end
    components
  end

  def self.large_graph_components
    edges = self.large_graph_edges
    components = []
    while edges.any? 
      component = edges.shift
      while edges.select { |edge| !(edge & component).empty? }.any?
        component << edges.select { |edge| !(edge & component).empty? }
        edges.delete_if { |edge| !(edge & component).empty? }
        component = component.flatten.uniq
      end
      components << component
    end
    components
  end

  def ensure_name_is_kanji_only
    if self.name.chars.any? { |char| char.ord < 19968 || char.ord > 40879 || char.ord == 12293 }
      errors.add(:name, "must be in kanji.")
    end
  end
end

app/controllers/surnames_controller.rb
class SurnamesController < ApplicationController
  before_action :set_surname, only: [:show, :edit, :update, :destroy]

  def histogram
    histogram_data = Surname.histogram_data
    render json: histogram_data
  end

  def directed_graph_small
    small_graph_data = Surname.small_graph_data
    render json: small_graph_data
  end

  def directed_graph_large
    large_graph_data = Surname.large_graph_data
    render json: large_graph_data
  end



  # GET /surnames
  # GET /surnames.json
  def index
    @surnames = Surname.all
  end

  # GET /surnames/1
  # GET /surnames/1.json
  def show
  end

  # GET /surnames/new
  def new
    @surname = Surname.new
  end

  # GET /surnames/1/edit
  def edit
  end

  # POST /surnames
  # POST /surnames.json
  def create
    @surname = Surname.new(surname_params)

    respond_to do |format|
      if @surname.save
        format.html { redirect_to @surname, notice: 'Surname was successfully created.' }
        format.js { render :js => "window.location = '/directed_graph_large'" }
      else
        format.html do
          render action: 'new'
        end
        format.js do
          render 'errors'
        end
      end
    end
  end

  # PATCH/PUT /surnames/1
  # PATCH/PUT /surnames/1.json
  def update
    respond_to do |format|
      if @surname.update(surname_params)
        format.html { redirect_to @surname, notice: 'Surname was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @surname }
      else
        format.html { render action: 'edit' }
        format.json { render json: @surname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surnames/1
  # DELETE /surnames/1.json
  def destroy
    @surname.destroy
    respond_to do |format|
      format.html { redirect_to surnames_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surname
      @surname = Surname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surname_params
      params.require(:surname).permit(:name)
    end
end

app/helpers/surnames_helper.rb
module SurnamesHelper
end

app/views/surnames/_errors.html.erb
<div id="error_explanation" class="remote_errors">
  <h2><%= pluralize(@surname.errors.count, "error") %> prohibited this surname from being saved:</h2>

  <ul>
    <% @surname.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/surnames/_form.html.erb
<%= form_for(@surname) do |f| %>
  <% if @surname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@surname.errors.count, "error") %> prohibited this surname from being saved:</h2>

      <ul>
      <% @surname.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surnames/_remote_form.html.erb
<%= form_for(@surname, :remote => true) do |f| %>
  <fieldset>
    <legend>New Surname</legend>
  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Add", :class => "btn btn-primary" %>
  </div>
</fieldset>
<% end %>

app/views/surnames/_surname.html.erb
<tr>
  <td><%= surname.name %></td>
  <td><%= link_to 'Show', surname %></td>
  <td><%= link_to 'Edit', edit_surname_path(surname) %></td>
  <td><%= link_to 'Destroy', surname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/surnames/edit.html.erb
<h1>Editing surname</h1>

<%= render 'form' %>

<%= link_to 'Show', @surname %> |
<%= link_to 'Back', surnames_path %>

app/views/surnames/errors.js.erb
$("#error_explanation").remove();
$("#new_surname").prepend("<%= j render 'errors' %>");

app/views/surnames/index.html.erb
<h1>Listing surnames</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surnames.each do |surname| %>
      <tr>
        <td><%= surname.name %></td>
        <td><%= link_to 'Show', surname %></td>
        <td><%= link_to 'Edit', edit_surname_path(surname) %></td>
        <td><%= link_to 'Destroy', surname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Surname', new_surname_path %>

app/views/surnames/new.html.erb
<h1>New surname</h1>

<%= render 'form' %>

<%= link_to 'Back', surnames_path %>

app/views/surnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @surname.name %>
</p>

<%= link_to 'Edit', edit_surname_path(@surname) %> |
<%= link_to 'Back', surnames_path %>